name: npm-publish-web-components
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.18.0
      - run: npm install
        working-directory: ./packages/web-components
      - run: npm run build
        working-directory: ./packages/web-components
      - uses: JS-DevTools/npm-publish@v1
        with:
          package:  ./packages/web-components/package.json
          token: ${{ secrets.NPM_AUTH_TOKEN }}